### ISSUE TITLE
GNOME Circle checklist

### ISSUE THREAD

**Issue by Jack5079** [mollersuite/tangent#5]
https://gitlab.gnome.org/Teams/Releng/AppOrganization/-/blob/main/AppCriteria.md

#### General Quality

  - [ ] Basic features and functionality work as expected
  - [ ] Easy to get started on first run
  - [ ] User reviews are generally positive. No repeated complaints about critical issues.
  - [ ] No known issues that can lead to data loss

#### Maintenance

  - [ ] Evidence of recent development activity
  - [ ] Confidence in the maintainers' ability to reliably maintain the project
  - [ ] Being careful about inflicting harm like data loss on users
  - [ ] Keeping up with maintenance to at least using a supported runtime on Flathub

#### Technology Basis

  - [x] Uses GTK 3 + Libhandy or GTK 4 + Libadwaita
      - [ ] GTK 3 + Libhandy apps should have plans for migrating to GTK 4
  - [ ] Uses the GNOME runtime on Flathub

#### Design

  - [ ] Follows the [Human Interface Guidelines](https://developer.gnome.org/hig/)
  - [ ] Dark mode works
      - [ ] Contrast is maintained everywhere (no dark font color on dark background etc.)
      - [ ] No white surfaces (apart from external media etc)

#### Content

  - [ ] Does not contradict the intentions of the [GNOME Code of Conduct](https://wiki.gnome.org/Foundation/CodeOfConduct)
  - [x] Does not promote cryptocurrencies or related services
      - *This would for example be the case if Tangent is focused on cryptocurrencies but **not if the app also supports features around cryptocurrencies without those being the priority**.*

#### Legal

  - [x] Has an [OSI-approved license](https://opensource.org/licenses)
  - [x] No contributor license agreement (CLA)
  - [ ] Tangent must work without installing proprietary software
  - [ ] Not already member of another non-profit fiscal sponsor organization
      - *This requirement is part of the Software Policy, but confusing. For more background and a clarification initiative see [Board Issue \#257](https://gitlab.gnome.org/Teams/Board/-/issues/257).*

#### Metadata

  - [ ] App name follows [guidelines](https://developer.gnome.org/hig/guidelines/app-naming.html)
	  - [x] Single noun
	  - [x] Be related to the app’s domain (for example: Celluloid for a video app)
		  - References both the rabbit holes Tangent is optimized for as well as our competitor Arc
	  - [x] Under 15 characters
	  - [x] Easy to pronounce
	  - [ ] Be easily paired with a good app icon, such as by referencing a physical object.
	  - [x] Use [header capitalization](https://developer.gnome.org/hig/guidelines/writing-style.html#header-capitalization) (for example: Icon Preview instead of Icon preview).
  - [x] #6
  - [ ] Screenshot quality ([more info](https://gitlab.gnome.org/GNOME/Initiatives/-/wikis/Update-App-Screenshots))
	  - [x] I use Plasma right now so I'll need to install GNOME
  - [x] #7
  - [ ] .doap-file in repository exists and is up-to-date ([more info](https://gitlab.gnome.org/World/apps-for-gnome/-/blob/main/METADATA.md#doap))

#### Accessibility

  - [ ] Can navigate to all elements via keyboard and use them
  - [ ] Uses standard keyboard shortcuts ([more info](https://developer.gnome.org/hig/reference/keyboard.html))
  - [ ] High-contrast mode works
  - [ ] Large text mode works
  - [ ] Sufficient contrast between content and background
  - [ ] Works with Orca (activate via `Alt+Super+S`)
      - [ ] Image buttons have a tooltip

#### Repository

  - [ ] Passing CI builds
  - [x] Public issue tracker and code repository
      - *The repository does *not* need to be hosted on GNOME's GitLab instance.*

### Recommended

  - [ ] Builds Flatpak in Builder out of the box
  - [ ] Build system is Meson, Automake, or CMake
  - [ ] Making contributors aware that the [GNOME Code of Conduct](https://wiki.gnome.org/Foundation/CodeOfConduct) applies to Tangent
      - *For example linking to the Code of Conduct in the README*

## Circle App Criteria

  - [ ] Fulfills the "General App Criteria"
  - [ ] Available on Flathub
      - [ ] Available for x64\_64 and aarch64
  - [x] No GNOME branding
      - *Tangent may not use GNOME in its name or its author field or be promoted as official GNOME software. However, after inclusion into GNOME Circle, the maintainers are encouraged to promote the app as being part of "GNOME Circle", using [the Circle branding](https://gitlab.gnome.org/Teams/Circle/-/tree/main/assets/button).*
  - [x] App ID is valid
	  - `uk.cetera.Tangent`
	  - [ ] do the `https://<something>.<public-suffix>/.well-known/org.flathub.VerifiedApps.txt` thing
  - [ ] Tangent supports internationalization and is connected to some localization infrastructure.

**Comment by Jack5079** [comment]
"Tangent" sounds too close to Tangram, another GNOME WebKitGTK app

**Comment by Jack5079** [comment]
Won't be a GTK app
